language: ruby
cache: bundler
before_install: gem install bundler -v 1.12.5
install: bundle install --without tools
rvm:
  - 2.3.1
  - 2.2.3
  - 2.0.0
  - ruby-head
  - jruby
gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/rails_5.gemfile
  allow_failures:
    - rvm: ruby-head
      rvm: jruby 
