language: ruby
cache: bundler
before_install:
  - gem update --system
  - gem --version
  - gem install bundler
  - gem update bundler
bundler_args: --without tools
rvm:
  - 2.3.1
  - 2.2.5
  - 2.0.0
  - ruby-head
  - jruby-head
  - rbx-2
gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile
matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/rails_5.gemfile
    - rvm: rbx-2
      gemfile: gemfiles/rails_5.gemfile
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head 
    - rvm: rbx-2
